import Groq from 'groq-sdk';
import * as dotenv from 'dotenv';

dotenv.config();

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

export async function askCodebase(query: string, codebaseContext: string): Promise<string> {
  const systemPrompt = `You are ContextOS, an expert engineering assistant.
You have been provided with the complete contents of a GitHub repository.
Please answer the developer's question based strictly on the provided codebase context.
Always cite specific files or functions in your answer. Focus on factual, grounded technical analysis.`;

  const userPrompt = `--- CODEBASE CONTEXT ---
${codebaseContext}
------------------------

Developer Question: ${query}`;

  try {
    const response = await groq.chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.3,
      max_tokens: 4096,
    });
    return response.choices[0]?.message?.content || "No answer generated by the LLM.";
  } catch (error: any) {
    console.error("LLM Error:", error);
    return `Error generating response from LLM: ${error.message}`;
  }
}
